apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tpa-tas-tap 
  janus-idp.io/tekton: tpa-tas-tap
  backstage.io/kubernetes-id: tpa-tas-tap
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tpa-tas-tap
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  