apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tpa-tas-tap
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tpa-tas-tap 
  name: tpa-tas-tap
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tpa-tas-tap 
